fail_fast: false
repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        stages: [commit]
        language: python
        types: [python]
        args: ["--check"]

      - id: isort
        name: isort
        entry: isort
        stages: [commit]
        language: python
        types: [python]
        args: ["--check-only"]

      - id: flake8
        name: flake8
        entry: flake8
        stages: [commit]
        language: python
        types: [python]
        args: ["--config", ".flake8"]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: requirements-txt-fixer # sort requirements